# Generated by Django 4.0.1 on 2022-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
